apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: midterm-alerts
  namespace: monitoring
spec:
  groups:
  - name: midterm.rules
    rules:
    - alert: PodRestartHigh
      expr: increase(kube_pod_container_status_restarts_total[10m]) > 3
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Pod restarted more than 3 times in 10 minutes"

    - alert: APISlowResponse
      expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, job)) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "API response time > 2s for 5 min"

    - alert: APIErrorRate
      expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "API error rate > 5% for 5 min"

    - alert: DiskUsageHigh
      expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 85
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Disk usage > 85%"
