groups:
- name: midterm-alerts
  rules:
  
  - alert: PodRestartHigh
    expr: increase(kube_pod_container_status_restarts_total[10m]) > 3
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Pod has restarted more than 3 times in 10 minutes"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting too often."

  
  - alert: HighAPIResponseTime
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "API response time high"
      description: "response time is above 2s"

  
  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High error rate"
      description: "In the last 5 minutes, More than 5% of api requests are errors"

  
  - alert: DiskUsageHigh
    expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.15
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Disk usage is above 85%"
      description: "Node {{ $labels.instance }} disk usage is above 85%"
